### ISSUE TITLE
Interfering with OneStepCheckout namespace

### ISSUE THREAD

**Issue by speedupmate** [wigman/AjaxSwatches#13]
see the file AjaxSwatches/app/code/community/Wigman/AjaxSwatches/etc/config.xml and search for OneStepCheckout https://www.dropbox.com/s/7e1h5jmrjlh65dq/Screenshot%202015-04-23%2015.21.33.png?dl=0 . Man you are interfering with other extension namespace and replacing the layout file with your own. 

Result is that clients probably go mad to find out why their checkout is not working

**Comment by wigman** [comment]
You are right. Oversaw this error after rolling back a commit at some point. I put it in while testing because my layout wasn't loading and couldn't figure out why. Did not realize this code was rolled back.
Thanks for spotting it.

**Comment by speedupmate** [comment]
Thank you for changing this . If you have a overview how many clients are using your extensions please notify all your clients about this issue and ask them to update. 

I'm not a preacher (just a support manager) but just that in the future you'd know the cost and reach of such mistakes. You have caused a lot of refund requests to other extension provider with this flaw. That's the cause what made me to spot this. Clients are unable to spot and debug such issues on their own and are using other extensions support lines to get things solved . Since you messed up a checkout on their site then they are really angry :)

**Comment by wigman** [comment]
Hi Speedupmate,

There are no clients of this extension, since I am not charging for it. Therefore I firstly have no idea who is using the extension because you can freely download it and secondly provide no guaranties. The target group is developers which I assume will never test a module like this on a live webshop.

The issue occurred in the last version and only affects users that have the onestepcheckout module installed. I have no idea how many people are having these issues, I only heard from 1 other person who had the problem.

Would you encourage me not to make any more free extensions? If the work I put in only results in 'really angry people' there's no use spilling my free time on it, right?

**Comment by speedupmate** [comment]
No, don't get me wrong, hack your way to the glory and probably at some point you just used OneStepCheckout  codebase as reference. Nothing wrong for you providing stuff for free and great that you reacted on my request so fast.

So to help you to learn more and encourage you to move forward I'm just providing the feedback here so you would see the reach and real world actions (install a free extension, mess up checkout, loose sales, loose hair , request a refund on extension that's not causing the issue) on simple typos. 

I can suggest that in the future you could use https://github.com/netz98/n98-magerun to generate the extension skeletons for you and you'll never make such mistakes again if you automate.
