### ISSUE TITLE
Possibility to make it work on any theme?

### ISSUE THREAD

**Issue by Marven-** [wigman/AjaxSwatches#5]
Hi,

I am not sure if this is the right place to post the question because it is not an issue. I am wondering if it is possible to make it work on any theme (I have ultimo theme installed).

Thanks

**Comment by nmjbteu** [comment]
Hi,

I am all so interested in same thing, I have ultimo 1.12 theme with magento 1.9.1... We have issues with simple products in configurable products... Default options is great, but lacks of one thing, showing images from simple product... Im ready to donate, if this modul would work on anytheme or ultimo...

Best regards

**Comment by wigman** [comment]
Hi Guys,

I looked at the latest Ultimo demo at http://ultimo.infortis-themes.com/demo/ and I can see that the 'official' swatches from Magento are being used. So I think the creator of the theme backported the official swatches from the RWD theme.

Therefore my plugin might just work when you install it. I have installed it for one client who is using the official swatches on a custom theme as well, without too many issues, but it depends on the theme really.

It's not possible for me to make it work on any theme ofcourse, because it hooks into the official plugin.

When you run into any problems you can contact me personally so we can figure something out.

**Comment by wigman** [comment]
As a follow up, here are details on my extension when using the Ultimo theme: https://github.com/wigman/AjaxSwatches/issues/8

**Comment by himani8** [comment]
Hi,
I have my custom theme,I tried your extension on rwd theme and it's working but in my theme it's not working. The ajax url is called is different.

**Comment by wigman** [comment]
Hi @himani8, that's not enough information to give you any advise. It would be best to investigate the differences between your theme and the RWD theme. Best would be to put a programmer on the job. Good luck.
