### ISSUE TITLE
Swatches image resize

### ISSUE THREAD

**Issue by virani06** [wigman/AjaxSwatches#6]
When i chane the image using swatches than image size will be change how to resize from base image

**Comment by ghost** [comment]
I noticed this on the category page when the product images are different sizes.

**Comment by wigman** [comment]
Hi. A demo url or a better description of your problem would help.
Also, please disable the plugin and check of the problem persists.
Since I'm not really changing the base functionality of the colorswatches I'm suspecting this problem is not related to my code.

Please share a url, or describe your problem. Don't forget to mention what Mage version, what other plugins and which theme you're using.

**Comment by HRR1337** [comment]
Hi there, Got a question. Is this modification also usable on a custom theme (like in my case Ultimo)? We have also big issues regarding performance on the category page with configurable swatches..

**Comment by ghost** [comment]
I didn't see this response but if you look at the demo http://staging.e-tailors.nl/magentodemo/men/shirts.html its noticable when you click a swatch under the plaid cotton shirt, the image grows.

**Comment by wigman** [comment]
I will have a look

**Comment by wigman** [comment]
Hey I checked it out and I found there's a difference in constrain setting between list and grids mode that's not taken in consideration in my code.
I will implement this functionality sometime soon.

**Comment by wigman** [comment]
I have fixed this in version 0.4.2. Please test and let me know how it goes.

**Comment by ghost** [comment]
Just like the demo that had the product image growing, now it appears if you have a smaller product image, it will resize it to its original size after a swatch is clicked. Doesn't happen if the product image is larger then the set image dimensions.

**Comment by wigman** [comment]
Hi Jupiter, I believe what you are describing is de default behaviour of the RWD theme. I am not able to make it fit to custom code but tried to make it as compatible as possible.
The plugin is meant for RWD primarily. What you want sounds like custom work you should get done, it won't end up in my plugin because it's not applicable to standard installs.
